### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by guchangan1** [914525753/Serverless_PortScan#1]
{"errno":403,"error":"requestId a7a7ffbd4edec4fc337aed3c8e9c1fb7 , Invalid scf response. expected scf response valid JSON.","message":"SCF invoke error"}

建议出一版详细配置教程

**Comment by shadowabi** [comment]
这个应该是函数的触发管理配置没配对，已经在readme.md中更新了一个触发管理的配置图。你可以对照一下，看看是否有不同的地方。
如果还有疑问的话，可以看看风起师傅的这篇云函数配置：https://www.anquanke.com/post/id/261551

**Comment by shadowabi** [comment]
现在已经新增详细教程在readme里了
